// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Testing.Server.Models;

namespace Testing.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Testing.Shared.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "SD"
                        },
                        new
                        {
                            ID = 2,
                            Name = "A"
                        },
                        new
                        {
                            ID = 3,
                            Name = "B"
                        });
                });

            modelBuilder.Entity("Testing.Shared.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentID1")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID1");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BirthDate = new DateTime(1998, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentID = "1",
                            Gender = 1,
                            LastName = "Smith",
                            Name = "Sam"
                        },
                        new
                        {
                            ID = 2,
                            BirthDate = new DateTime(1996, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentID = "2",
                            Gender = 0,
                            LastName = "Fuentes",
                            Name = "Andrés"
                        },
                        new
                        {
                            ID = 3,
                            BirthDate = new DateTime(2007, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentID = "3",
                            Gender = 0,
                            LastName = "Hatsune",
                            Name = "Miku"
                        });
                });

            modelBuilder.Entity("Testing.Shared.Employee", b =>
                {
                    b.HasOne("Testing.Shared.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID1");

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
